version: '3'

networks:
  backend:
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "10000:80"
      - "10001:443"
    volumes:
      - ./:/var/www/stocker
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - redis
      - mysql
      - php
      - node
      - python
    networks:
      backend:
        ipv4_address: 172.22.0.2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "10002:6379"
    networks:
      backend:
        ipv4_address: 172.22.0.3

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "10003:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password --skip_name_resolve --innodb-use-native-aio=0
    networks:
      backend:
        ipv4_address: 172.22.0.4

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    ports:
      - "10004:9000"
    volumes:
      - ./:/var/www/stocker
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      backend:
        ipv4_address: 172.22.0.5

  node:
    image: node:slim
    container_name: node
    volumes:
      - ./:/var/www/stocker
    working_dir: /var/www/stocker
    networks:
      backend:
        ipv4_address: 172.22.0.6
    tty: true

  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: python
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
    ports:
      - "10005:5000"
    volumes:
      - ./python:/run
    networks:
      backend:
        ipv4_address: 172.22.0.7
